spring:
  application:
    name: mig-back-to-basics
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mig_basics
      username: root
      password: example
  datasource:
    url: jdbc:mysql://localhost:3306/mig_basics
    username: root
    password:
#  jpa:
#    hibernate:
#      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Spring MIG Back to Basics
    version: 1.0.0
    description: Our first application

mig:
  repository-type: http
  http:
    url: http://localhost:8888
    username: user
    password: pass123
